version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - instance1
        - instance2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # generates instance1
  instance1:
    image: parking:1.0
    container_name: instance1
    ports:
      - 9000:8080
    restart: on-failure

  # generates instance2
  instance2:
    image: parking:1.0
    container_name: instance2
    ports:
      - 9001:8080
    restart: on-failure