version: '3'

services:

  # Proxies requests to internal services
  Ngnix:
    image: skumar357/parkinglotnginx:1.0
    container_name: nginx
    depends_on:
        - instance1
        - Redis
    ports:
      - 80:80

  # generates instance1
  instance1:
    image: skumar357/parkinglotmanagement:2.0
    container_name: instance1
    ports:
      - 9000:8080
    depends_on:
      - Redis
    restart: on-failure

  # generates instance2
  instance2:
    image: skumar357/parkinglotmanagement:2.0
    container_name: instance2
    ports:
      - 9001:8080
    depends_on:
      - Redis
    restart: on-failure

  # running redis
  Redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: on-failure